import type { Metadata } from "next";
import { getCssText, styled } from "@/lib/stitches.config";
import { Header } from "@site/ui";

export const metadata: Metadata = {
  title: "Luis Gustavo | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>

      <Body>
        <Header />
        {children}
      </Body>
    </html>
  );
}

const Body = styled("body", {
  backgroundColor: "$surfaceContainerLowest",
});
