import type { Metadata } from "next";
import { Drawer } from "@site/ui";
import { getCssText, styled } from "@/lib/stitches.config";

export const metadata: Metadata = {
  title: "Luis Gustavo | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>

      <Body>
        <Drawer>{children}</Drawer>
      </Body>
    </html>
  );
}

const Body = styled("body", {
  backgroundColor: "$white700",
});
