import { ReactElement } from "react";
import type { Metadata } from "next";
import { Drawer } from "@site/Drawer";
import { TopBar } from "@site/TopBar";
import { getCssText, styled } from "@/lib/stitches.config";

export const metadata: Metadata = {
  title: "Luis Gustavo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>

      <Body>
        <Drawer TopBar={<TopBar />} Content={children} />
      </Body>
    </html>
  );
}

const Body = styled("body", {
  backgroundColor: "$white700",
});
