name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install and Build
        run: npm install && npm run build

      - name: Deploy to luisao.xyz
        run: aws s3 sync ./out s3://luisao.xyz --delete --include "*"
